name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Compress project files (excluding .git, node_modules, build)
        run: |
          # Create tar.gz in /tmp to avoid archiving itself
          tar --exclude='.git' --exclude='node_modules' --exclude='build' \
              -czf /tmp/app.tar.gz .
          mkdir -p build
          mv /tmp/app.tar.gz build/app.tar.gz

      - name: Copy project to EC2
        run: |
          echo "Deploying to: ec2-user@${{ secrets.EC2_HOST }}"
          scp -o StrictHostKeyChecking=no -i ec2_key.pem build/app.tar.gz ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Extract and deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'

            rm -rf /home/ec2-user/app
            mkdir /home/ec2-user/app
            tar -xzf /home/ec2-user/app.tar.gz -C /home/ec2-user/app
            rm /home/ec2-user/app.tar.gz

            cd /home/ec2-user/app

            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
            echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
            echo "PROTECTED_USERS=${{ secrets.PROTECTED_USERS }}" >> .env
            echo "NODE_ENV=production" >> .env
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env

            docker stop mflix || true
            docker rm mflix || true
            docker build -t mflix-api ./server
            PORT=$(grep PORT .env | cut -d '=' -f2)
            docker run -d -p $PORT:$PORT --env-file .env --name mflix mflix-api
          EOF
